#!/usr/bin/env python3
"""Build the sensor-degradation tables (Tables 9 and 10) from the sweep results on disk.

    python scripts/ablation_table.py
    python scripts/ablation_table.py --results eval_results --out-dir tables

Reads the sweeps written by ``scripts/run_sweep.sh``:

* ``ablation_<env>/<model>_<condition>_{obs,both}``  (config/eval_sweep/ablation_<env>.conf),
* ``ablation_t2l_<env>/<model>_{mlp,mlp_z}_<condition>_obs``  (ablation_t2l_<env>.conf),
* the clean reference of each model: ``ablation_<env>/<model>_clean``, or, when that row
  has not been run, the ``lidar_<env>/<model>`` row of the Table 2 sweep (same checkpoint,
  same seeds, same start-goal windows).

As in the paper, every degraded cell is reported RELATIVE to the model's clean success rate:
``100 * mean / clean_mean`` with the spread ``100 * sd / clean_mean`` (sd across seeds), so
100 means no degradation and values above 100 lie within seed noise. The clean row itself is
printed in absolute terms.

Writes ``<out-dir>/table9_degradation.tex`` (observation degraded with a clean goal cloud, and
observation and goal cloud degraded alike) and ``<out-dir>/table10_t2l_degradation.tex`` (the
goal-cloud planner under joint degradation, "Base", against the target-to-latent heads +MLP
and +MLP_z, which receive the clean 3D target). Cells without results print as ``--``.
Standard library only, and success rates are parsed with the same pattern as
``scripts/summarize_evals.py``, so the two never disagree about a number.
"""

import argparse
import re
import statistics
import sys
from pathlib import Path

SUCCESS_RE = re.compile(r"['\"]success_rate['\"]:\s*(?:np\.float\d+\()?([0-9.eE+-]+)")
SEED_DIR_RE = re.compile(r"^seed(-?\d+)$")

ENVS = [("tworoom", "Two-Room"), ("reacher", "Reacher"), ("pusht", "Push-T"), ("cube", "OGB-Cube")]
MODELS = [("point_lewm", "P-LeWM"), ("point_delta_jepa", "PD-JEPA")]
# condition key | LaTeX label -- the levels defined in scripts/gen_ablation_confs.py
CONDITIONS = [
    ("noise0025", r"Noise $0.25\%$"),
    ("noise005", r"Noise $0.5\%$"),
    ("drop25", r"Dropout $25\%$"),
    ("drop50", r"Dropout $50\%$"),
]


def read_rate(path):
    """Success rate of the LAST result block of a results.txt (the scripts append)."""
    hits = SUCCESS_RE.findall(path.read_text(errors="replace"))
    return (float(hits[-1]), len(hits)) if hits else (None, 0)


def label_rates(roots, sweep, label, stale):
    """{seed: rate} of one sweep label, merged over the results roots."""
    rates = {}
    for root in roots:
        d = Path(root) / sweep / label
        if not d.is_dir():
            continue
        for seed_dir in d.iterdir():
            m = SEED_DIR_RE.match(seed_dir.name)
            f = seed_dir / "results.txt"
            if not m or not f.is_file():
                continue
            rate, n = read_rate(f)
            if rate is None:
                continue
            if n > 1:
                stale.append(f"{f} ({n} result blocks, the last one is used)")
            rates[int(m.group(1))] = rate
    return rates


def stats(rates):
    vals = list(rates.values())
    if not vals:
        return None
    return statistics.fmean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0), len(vals)


def clean_reference(roots, env, model, stale):
    """(mean, sd, n, source) of the model's clean success rate, or None."""
    for sweep, label in ((f"ablation_{env}", f"{model}_clean"), (f"lidar_{env}", model)):
        s = stats(label_rates(roots, sweep, label, stale))
        if s:
            return (*s, f"{sweep}/{label}")
    return None


def relative(roots, sweep, label, clean, stale):
    s = stats(label_rates(roots, sweep, label, stale))
    if s is None or clean is None or clean[0] == 0:
        return None
    mean, sd, n = s
    return 100.0 * mean / clean[0], 100.0 * sd / clean[0], n


def fmt(cell):
    return "--" if cell is None else f"{cell[0]:.1f}\\sd{{{cell[1]:.1f}}}"


def table9(roots, cleans, stale):
    cols = [(env, model) for env, _ in ENVS for model, _ in MODELS]
    head = " & ".join(rf"\multicolumn{{2}}{{c}}{{{name}}}" for _, name in ENVS)
    sub = " & ".join(name for _ in ENVS for _, name in MODELS)
    lines = [
        r"% Generated by scripts/ablation_table.py -- do not edit by hand.",
        r"\begin{tabular}{l" + "c" * len(cols) + "}",
        r"  \toprule",
        rf"  & {head} \\",
        rf"  \textbf{{Perturbation}} & {sub} \\",
        r"  \midrule",
        "  None & " + " & ".join(fmt(cleans.get(c)) for c in cols) + r" \\",
    ]
    for scope, title in (("obs", "Observation degraded, goal clean"), ("both", r"Observation \emph{and} goal degraded")):
        lines += [r"  \midrule", rf"  \multicolumn{{{len(cols) + 1}}}{{l}}{{\emph{{{title}}}}} \\"]
        for key, name in CONDITIONS:
            cells = [relative(roots, f"ablation_{env}", f"{model}_{key}_{scope}", cleans.get((env, model)), stale)
                     for env, model in cols]
            lines.append(f"  {name} & " + " & ".join(fmt(c) for c in cells) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def table10(roots, cleans, stale):
    lines = [
        r"% Generated by scripts/ablation_table.py -- do not edit by hand.",
        r"\begin{tabular}{llcccccc}",
        r"  \toprule",
        r"  & & \multicolumn{3}{c}{P-LeWM} & \multicolumn{3}{c}{PD-JEPA} \\",
        r"  \textbf{Env.} & \textbf{Perturbation} & Base & +MLP & +MLP\textsubscript{z} & Base & +MLP & +MLP\textsubscript{z} \\",
    ]
    for env, env_name in ENVS:
        lines.append(r"  \midrule")
        for j, (key, name) in enumerate(CONDITIONS):
            cells = []
            for model, _ in MODELS:
                clean = cleans.get((env, model))
                cells.append(relative(roots, f"ablation_{env}", f"{model}_{key}_both", clean, stale))
                for head in ("mlp", "mlp_z"):
                    cells.append(relative(roots, f"ablation_t2l_{env}", f"{model}_{head}_{key}_obs", clean, stale))
            first = rf"\multirow{{{len(CONDITIONS)}}}{{*}}{{{env_name}}}" if j == 0 else ""
            lines.append(f"  {first} & {name} & " + " & ".join(fmt(c) for c in cells) + r" \\")
    lines += [r"  \bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", action="append", default=None,
                    help="results root to scan; repeatable (default: $PLWM_RESULTS_ROOT or eval_results/)")
    ap.add_argument("--out-dir", type=Path, default=Path("tables"))
    args = ap.parse_args()
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from paths import RESULTS_ROOT

    roots = args.results or [RESULTS_ROOT]
    stale = []
    cleans = {}
    print("clean references (absolute success rate, %):")
    for env, env_name in ENVS:
        for model, model_name in MODELS:
            c = clean_reference(roots, env, model, stale)
            if c:
                cleans[(env, model)] = c
                print(f"  {env_name:9s} {model_name:8s} {c[0]:5.1f} +- {c[1]:4.1f}  (n={c[2]}, {c[3]})")
            else:
                print(f"  {env_name:9s} {model_name:8s}    --  (no clean row: run ablation_{env}.conf or lidar_{env}.conf)")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    t9 = args.out_dir / "table9_degradation.tex"
    t10 = args.out_dir / "table10_t2l_degradation.tex"
    t9.write_text(table9(roots, cleans, stale))
    t10.write_text(table10(roots, cleans, stale))

    print("\nrelative success (% of clean), mean over seeds:")
    print(f"  {'env':9s} {'model':8s} " + " ".join(f"{k + '_' + s:>15s}" for k, _ in CONDITIONS for s in ("obs", "both")))
    for env, env_name in ENVS:
        for model, model_name in MODELS:
            row = [relative(roots, f"ablation_{env}", f"{model}_{k}_{s}", cleans.get((env, model)), stale)
                   for k, _ in CONDITIONS for s in ("obs", "both")]
            if any(row):
                print(f"  {env_name:9s} {model_name:8s} " + " ".join(f"{c[0]:>15.1f}" if c else f"{'--':>15s}" for c in row))
    if stale:
        print("\nWARNING: results.txt files with more than one result block:")
        for s in sorted(set(stale))[:10]:
            print("  " + s)
    print(f"\nwrote {t9} and {t10}")


if __name__ == "__main__":
    main()
