#!/usr/bin/env python3
"""Generate the sensor-degradation sweep configs from one definition of the levels.

    python scripts/gen_ablation_confs.py            # writes config/eval_sweep/ablation_*.conf
    python scripts/gen_ablation_confs.py --dry-run  # only prints what it would write

Two families of sweeps come out of this script, four environments each:

* ``ablation_<env>.conf`` (Table 9): Point-LeWM and Point-Delta-JEPA planning
  toward the recorded goal cloud while the live scan is degraded (``_obs``), or
  the live scan and the goal cloud alike (``_both``).
* ``ablation_t2l_<env>.conf`` (Table 10): the same observation degradation, but
  the goal latent is predicted from the clean 3D target by the ``mlp`` and
  ``mlp_z`` target-to-latent heads (the goal is a pose, so there is no goal
  cloud to degrade; only the ``_obs`` scope exists here).

The perturbation levels live HERE, once, so the eight files cannot drift apart.
Both knobs are eval-time only (``lidar.perturb`` in the eval configs):

  noise_frac    Gaussian range noise along each point's line of sight, sigma as a
                fraction of that frame's scan bounding-box diagonal. Relative,
                because an absolute sigma means different things in the 4.9 m
                Push-T arena and the 1.4 m Reacher workspace. Both levels stay below the median point
                spacing (about 0.33x and 0.67x of it in every environment), so a
                surface softens instead of dissolving.
  dropout_prob  fraction of returns marked as misses; they leave through the same
                invalid-value filter as genuine misses.

Every row shares the checkpoint, the seeds and the start-goal windows with the
clean baseline sweep of the same environment (``lidar_<env>.conf`` for Table 9,
``3dtarget_<env>_<model>.conf`` for Table 10), which is what the relative numbers
of the paper are computed against. Inspect a level before spending a sweep on it
with ``python scripts/perturb_inspect.py --env <env>``.
"""

import argparse
from pathlib import Path

ENVS = ["tworoom", "reacher", "pusht", "cube"]
PRETTY = {"tworoom": "Two-Room", "reacher": "Reacher", "pusht": "Push-T", "cube": "OGB-Cube"}
SEEDS = "SEEDS=(1 25 35 36 40 42 65 80 83 99)"

#: the checkpoint each arm evaluates: the released one under
#: checkpoints/<env>/<model>/ (scripts/download_checkpoints.py). For a training
#: run of your own use "run=<run folder> policy=<export inside it>" instead.
MODEL_DIR = {"point_lewm": "point-lewm", "point_delta_jepa": "point-delta-jepa"}


def checkpoint(model, env):
    return f"cache_dir=. policy={env}/{MODEL_DIR[model]}/weights.pt"


# (label suffix, overrides); low -> high within each family
CONDITIONS_OBS = [
    ("noise0025_obs", "lidar.perturb.noise_frac=0.0025"),
    ("noise005_obs", "lidar.perturb.noise_frac=0.005"),
    ("drop25_obs", "lidar.perturb.dropout_prob=0.25"),
    ("drop50_obs", "lidar.perturb.dropout_prob=0.5"),
]
CONDITIONS_BOTH = [(s.replace("_obs", "_both"), o + " lidar.perturb.scope=both") for s, o in CONDITIONS_OBS]

HEADER = """# ===========================================================================
#  {title}
#
#  GENERATED by scripts/gen_ablation_confs.py: edit the levels there, not here.
#
{body}
#
#  Run from the repository root:
#      pixi run bash scripts/run_sweep.sh config/eval_sweep/{name}.conf   [--dry-run] [--seeds "1 42"]
#      python scripts/summarize_evals.py eval_results/{name}
#      python scripts/ablation_table.py            # the relative-success tables
# ===========================================================================

SWEEP_NAME={name}
EVAL_CONFIG={cfg}
EVAL_TASK={task}
NUM_EVAL=50
# The SAME ten seeds as the clean baseline sweeps, so every degraded row is
# averaged over the same evaluation windows as the clean row it is read against.
{seeds}

EVALS=(
{evals})

COMMON_OVERRIDES=(
{common})
SAVE_VIDEOS=false
"""


def rows(entries):
    width = max(len(label) for label, _ in entries)
    return "".join(f'  "{label.ljust(width)} | {ovr}"\n' for label, ovr in entries)


def table9(env):
    entries = []
    for model in ["point_lewm", "point_delta_jepa"]:
        base = f"{checkpoint(model, env)} planner=cem"
        # the clean row is the reference every relative number is computed against
        entries.append((f"{model}_clean", base))
        for suffix, ovr in CONDITIONS_OBS + CONDITIONS_BOTH:
            entries.append((f"{model}_{suffix}", f"{base} {ovr}"))
    body = "\n".join(f"#  {l}" for l in [
        f"Table 9, {PRETTY[env]}: Point-LeWM and Point-Delta-JEPA under a degraded sensor.",
        "_obs rows degrade the live observation only (a worse sensor pursuing a stored",
        "target); _both rows degrade the goal cloud identically. The clean reference is",
        f"config/eval_sweep/lidar_{env}.conf.",
    ])
    return HEADER.format(title=f"SENSOR DEGRADATION, {PRETTY[env]}", body=body, name=f"ablation_{env}",
                         cfg=f"lidar_{env}", task="eval-lidar", seeds=SEEDS, evals=rows(entries), common="")


def table10(env):
    entries = []
    for model in ["point_lewm", "point_delta_jepa"]:
        ckpt = checkpoint(model, env)
        for head in ["mlp", "mlp_z"]:
            model_dir = f"checkpoints/{env}/{MODEL_DIR[model]}/target2latent/{head}"
            for suffix, ovr in CONDITIONS_OBS:
                entries.append((f"{model}_{head}_{suffix}", f"{ckpt} target_goal.model_dir={model_dir} {ovr}"))
    body = "\n".join(f"#  {l}" for l in [
        f"Table 10, {PRETTY[env]}: the target-to-latent heads (mlp, mlp_z) under the same",
        "observation degradation as Table 9. The goal enters as a clean 3D target, so",
        "only the _obs scope exists. The clean references are the t2l_mlp / t2l_mlp_z",
        f"rows of config/eval_sweep/3dtarget_{env}_<model>.conf, paired on the same",
        "pinned start lists (eval_starts/).",
    ])
    common = (f"  'eval.starts_file=eval_starts/starts_{env}_seed${{seed}}.json'\n"
              "  target_goal.video=false\n")
    return HEADER.format(title=f"SENSOR DEGRADATION WITH 3D TARGETS, {PRETTY[env]}", body=body,
                         name=f"ablation_t2l_{env}", cfg=f"3dtarget_{env}", task="eval-3dtarget",
                         seeds=SEEDS, evals=rows(entries), common=common)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    out = Path("config/eval_sweep")
    for env in ENVS:
        for name, text in [(f"ablation_{env}", table9(env)), (f"ablation_t2l_{env}", table10(env))]:
            n = text.count('\n  "')
            print(f"  {name:24s} {n:2d} rows")
            if not args.dry_run:
                (out / f"{name}.conf").write_text(text)


if __name__ == "__main__":
    main()
