#!/usr/bin/env python3
"""Emit the commanded-goal grid sweep config (App. D.2.1, Figure 5, Table 11).

From the repository root, after scripts/cube_grid_goals.py has written the grid
files::

    pixi run python scripts/gen_cube_grid_conf.py
    pixi run python scripts/gen_cube_grid_conf.py --starts 0 1 --layers 4 --out /dev/stdout

The sweep is a full crossing of

    2 goal sources  x  5 designed grasped starts  x  5 height layers  =  50 items

and each item needs its own ``eval.grid_file`` (which start), ``eval.grid_block``
(which layer) and ``eval.num_eval`` (that layer's goal count -- the layers hold
33-42 goals, because goals too close to a start are dropped). Writing 50 entries
by hand invites exactly the kind of silent mismatch -- a layer run with another
layer's goal count -- that eval_3dtarget.py would have to reject at load time, so
they are generated from the grid files themselves.

THE TWO ARMS
  t2l_mlp_z   the goal head: an MLP conditioned on the commanded 3-D position
              and on z_now, the latent of the current observation
  goalcloud   the rebuilt goal cloud: the environment set to the commanded pose
              (cube held by an IK-posed arm) and re-scanned, then encoded. This
              is the strongest goal-cloud baseline obtainable in simulation --
              not retrieval of a nearby recorded frame -- and
              scripts/cube_goal_scans.py validates it against recorded
              observations before writing it.

Replication is over the five STARTS, not over evaluation seeds: no head is
retrained here, so a second seed would only resample planner and encoder noise,
while a second start asks whether the ranking survives commanding the same goals
from a different corner of the workspace.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # repo root, for paths.py
from paths import LOGS_ROOT, T2L_ROOT  # noqa: E402  (T2L_ROOT: where the grid artefacts live)

HEADER = """\
# ===========================================================================
#  App. D.2.1, Figure 5 and Table 11: commanding goals the expert never aimed at
#
#  GENERATED by scripts/gen_cube_grid_conf.py -- edit that, not this file.
#
#  THE QUESTION. Commanded 3-D cube positions on height layers, each approached
#  from five designed grasped starts. Every recorded goal in the dataset is a
#  placement on the table (z = 0.02 m), so every layer above it is a goal regime
#  the expert never aimed at, while staying inside the arm's workspace.
#
#  THE COMPARISON. The target-to-latent head against the REBUILT goal cloud --
#  the environment set to the commanded pose and re-scanned
#  (scripts/cube_goal_scans.py), which is the strongest goal observation
#  obtainable in simulation. Retrieval of a nearby recorded frame is
#  deliberately NOT the baseline here: it would lose for reasons of proximity
#  rather than of representation.
#
#  PREREQUISITES, in this order:
#    1. a trained Point-Delta-JEPA OGB-Cube world model and its target-to-latent
#       heads (docs/training.md)
#    2. pixi run python scripts/cube_grid_goals.py  -> cube_grid_goals_s0..s4.json
#    3. pixi run python scripts/cube_goal_scans.py  -> cube_goal_scans.npz
#       (it refuses to write unless its fidelity check passes)
#    4. pixi run python -m pytest tests/test_cube_grid.py
#
#  Run from the repository root:
#      pixi run bash scripts/run_sweep.sh config/eval_sweep/<this file>   [--dry-run]
#  and aggregate with
#      pixi run python scripts/cube_grid_stats.py        # Table 11
#      pixi run python scripts/plot_cube_goals_pair.py   # Figure 5
#
#  Every entry of EVALS is "<label> | <hydra overrides>". Unlike the Table 2
#  sweeps this one repeats over STARTS, not over seeds: nothing is retrained, so
#  a second seed would only resample planner and encoder noise, while a second
#  start re-asks the question from another corner of the workspace.
# ===========================================================================

SWEEP_NAME={sweep}
EVAL_CONFIG=3dtarget_cube_grid
EVAL_TASK=eval-3dtarget

# Per-item eval.num_eval overrides this (the layers differ in size); it is set
# because run_sweep.sh requires it and passes it before the per-item overrides.
NUM_EVAL={num_eval_default}

# ONE evaluation seed on purpose -- see the note above.
SEEDS=(42)

# The released Point-Delta-JEPA OGB-Cube checkpoint and its target-to-latent heads
# (checkpoints/cube/, scripts/download_checkpoints.py). To use your own training
# run instead, regenerate with
#   --ckpt "run=<run folder under experiment_logs> policy=<export inside it>" --head-dir <dir>
CKPT="{ckpt}"
M={head_dir}
G=${{PLWM_T2L_ROOT:-experiment_logs/target2latent}}/grid
EVALS=(
{evals}
)

COMMON_OVERRIDES=(
  target_goal.video=false
)
SAVE_VIDEOS=false
"""

ARM_OVERRIDES = {
    "t2l_mlp_z": "${CKPT} target_goal.model_dir=${M}/mlp_z",
    "t2l_mlp": "${CKPT} target_goal.model_dir=${M}/mlp",
    "goalcloud": ("${CKPT} target_goal.goal_mode=true "
                  "eval.grid_scans=${G}/cube_goal_scans.npz"),
    "retrieval": "${CKPT} target_goal.goal_mode=true eval.grid_retrieval=true",
}


def run_name(ckpt):
    """The ``run=`` value of a checkpoint override string, or "" when absent."""
    return next((v for k, _, v in (x.partition("=") for x in ckpt.split()) if k == "run"), "")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--grid", type=Path, default=Path(T2L_ROOT) / "grid",
                    help="where cube_grid_goals.py wrote; read to learn each layer's size")
    ap.add_argument("--starts", type=int, nargs="+", default=[0, 1, 2, 3, 4])
    ap.add_argument("--layers", type=int, nargs="+", default=None, help="default: all")
    ap.add_argument("--arms", nargs="+", default=["t2l_mlp_z", "goalcloud"],
                    choices=sorted(ARM_OVERRIDES))
    ap.add_argument("--sweep", default="3dtarget_cube_grid")
    ap.add_argument("--ckpt", default="cache_dir=. policy=cube/point-delta-jepa/weights.pt",
                    help="the world-model overrides every item carries; the default is the "
                         "released OGB-Cube checkpoint. For a training run of your own: "
                         "\"run=<folder> policy=<folder>/weights_final.pt\"")
    ap.add_argument("--head-dir", default="checkpoints/cube/point-delta-jepa/target2latent",
                    help="folder holding the target-to-latent heads (mlp/, mlp_z/ inside)")
    ap.add_argument("--out", type=Path,
                    default=Path("config/eval_sweep/3dtarget_cube_grid.conf"))
    ap.add_argument("--no-check", action="store_true",
                    help="skip the existence check of the paths the config names")
    args = ap.parse_args()

    specs = {}
    for s in args.starts:
        f = args.grid / f"cube_grid_goals_s{s}.json"
        if not f.is_file():
            raise SystemExit(f"missing {f} -- run scripts/cube_grid_goals.py first")
        specs[s] = json.loads(f.read_text())
    n_layers = len(specs[args.starts[0]]["blocks"])
    layers = args.layers if args.layers is not None else list(range(n_layers))

    # every start must command the same goals, or the items are not comparable
    ref = [b["goals"] for b in specs[args.starts[0]]["blocks"]]
    for s, spec in specs.items():
        if [b["goals"] for b in spec["blocks"]] != ref:
            raise SystemExit(f"start {s} commands a different goal set -- regenerate the grid")

    lines, n = [], 0
    for arm in args.arms:
        for s in args.starts:
            for bi in layers:
                b = specs[s]["blocks"][bi]
                z = int(round(b["height_m"] * 100))
                label = f"{arm}_z{z}_s{s}"
                lines.append(f'  "{label:<24s}| {ARM_OVERRIDES[arm]} '
                             f'eval.grid_file=${{G}}/cube_grid_goals_s{s}.json '
                             f'eval.grid_block={bi} eval.num_eval={b["n_goals"]}"')
                n += 1

    # fail here, not half way through a 50-item sweep: every artefact the
    # config names must already exist
    if not args.no_check:
        need = [args.grid / "cube_goal_scans.npz"] if "goalcloud" in args.arms else []
        need += [Path(args.head_dir) / a.split("t2l_")[-1]
                 for a in args.arms if a.startswith("t2l_")]
        for tok in args.ckpt.split():
            key, _, val = tok.partition("=")
            if key == "policy":
                root = next((v for k, _, v in (x.partition("=") for x in args.ckpt.split())
                             if k == "cache_dir"), None)
                need.append((Path(root) if root else Path(LOGS_ROOT) / run_name(args.ckpt))
                            / "checkpoints" / val)
        missing = [p for p in need if not p.exists()]
        if missing:
            raise SystemExit("the config would name these, but they do not exist "
                             "(pass --no-check to write it anyway):\n"
                             + "\n".join(f"  {p}" for p in missing))

    text = HEADER.format(
        sweep=args.sweep, ckpt=args.ckpt, head_dir=args.head_dir,
        num_eval_default=specs[args.starts[0]]["blocks"][layers[0]]["n_goals"],
        evals="\n".join(lines))
    args.out.write_text(text)
    print(f"{n} items ({len(args.arms)} arms x {len(args.starts)} starts x "
          f"{len(layers)} layers) -> {args.out}")


if __name__ == "__main__":
    main()
